betas:
- 0.9
- 0.95
bs: 64
data:
  shuffle: true
  test_root: ./data/processed/test
  train_root: ./data/processed/train
exp_name: debug
gpus:
- -1
load_ckpt_pth: null
load_optimizer: false
log:
  enable_async: true
  images: true
  num_threads: 4
  save_best: false
  save_freq: 1000
  save_init: false
  save_last: false
  test_freq: 500
  train_freq: 100
  uri: ~/dev/dl-schema/dl_schema/mlruns
loss: crossentropy
lr: 0.0003
lr_method: onecycle
metric1: accuracy
model:
  dropout1: 0.25
  dropout2: 0.5
  fc_units: 128
  in_channels: 1
  model_class: BabyCNN
  out_features: 10
num_workers: 4
onecycle_div_factor: 25
onecycle_final_div_factor: 10000.0
resume: false
run_name: run_0
seed: 42
train_steps: 2000
tune: false
weight_decay: 0.0
